version: '3.7'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: bpapp-server
    container_name: bpapp-node-server
    command: npm run server
    volumes:
      - ./server/:/server
      - /server/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file: ./server/.env
    environment:
      - NODE_ENV=development
    networks:
      - app-network
  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: bpapp-client
    container_name: bpapp-react-client
    command: npm run start
    volumes:
      - ./client/:/client
      - /client/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
    stdin_open: true
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local